services:
  image-service:
    build: .
    container_name: image-service
    ports:
      - "5000:5000"
    volumes:
      - ./outputs:/app/outputs
      - ./models:/app/models
      - ./.env:/app/.env:ro
      # AMD WSL2 GPU support
      - /usr/lib/wsl/lib/libdxcore.so:/usr/lib/libdxcore.so
      - /opt/rocm/lib/libhsa-runtime64.so.1:/opt/rocm/lib/libhsa-runtime64.so.1
    environment:
      - PYTHONUNBUFFERED=1
      - HSA_ENABLE_SDMA=0
      - PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:2048
      - TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL=1
    devices:
      - /dev/dxg
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ipc: host
    shm_size: 8G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s